### ISSUE TITLE
elseif startTarget evaluation to disable valve does not work

### ISSUE THREAD

**Issue by eLuke455** [eklex/AutoIrrigation#1]
In the following code:

```
if(runTarget && !startTarget)       startTarget = true;
else if(!runTarget && startTarget)  startTarget = false;
```

the 2nd evaluation will never be true because the variable is defined inside the main loop as
 boolean   startTarget = false;

At least, thats what my debugging has shown. The issue does not manifest itself when you only have one pinvalve, but after modifying code for 4 valves it was not turning off valves.

**Comment by eklex** [comment]
Hi @eLuke455. Actually the variable _startTarget_ gets initialized just once, since the code drops in the while-loop and stays in this loop. If you want to ensure it is initialized only once, you can prefix the declaration with **static**.

I dont see any issue with the code even if you use 4 valves. I think the 1st thing to try is to validate that the valve outputs are set to high when starting the uC, and go back to low within a minute. If it's not the case, it could be a problem with the RTC, OR the way you configured the outputs, OR your scheduled hours that set _runTarget_ to always true.

**Comment by eLuke455** [comment]
Thanks for the response. You helped me to answer the problem and was my fault. 

I copied your code into a different sketch (as I am using different RTC drivers) and in the process I dropped the while loop,and therefore the variables were always being reinitialised upon each loop. 

I have it working now with four valves .. thanks.

Luke
